name: vol
description: "Eco Volunteer App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  go_router: ^15.2.3
  video_player: ^2.8.2
  cached_network_image: ^3.3.1
  responsive_framework: ^1.1.0
  data_table_2: ^2.5.8
  http: ^0.13.6
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  path_provider: ^2.0.12
  fluttertoast: ^8.2.4
  flutter_animate: ^4.1.1
  url_launcher: ^6.1.11
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/eco_logo.png"
  adaptive_icon_background: "assets/images/eco_logo.png"
  adaptive_icon_foreground: "assets/images/eco_logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/eco_logo.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/pin_plastic.png
    - assets/images/pin_organic.png
    - assets/images/pin_hazard.png
    - assets/images/pin_general.png
